baseURL = "https://cucumber-sandwiches.github.io/"
languageCode = "en-gb"
title = "Cucumber Sandwiches And Tea"
theme = "recipes"

[params]
  author = "Anne & Matthias"
  description = "Anne & Matthias' Recipe Book"
